// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8XPIla0vpUdWCZw_L29RaofSWjThKh_o',
    appId: '1:69161896679:web:a87aa40ac8561718037042',
    messagingSenderId: '69161896679',
    projectId: 'builder-jobs-app',
    authDomain: 'builder-jobs-app.firebaseapp.com',
    storageBucket: 'builder-jobs-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANeE1AilQtGNudfD3XPvof-CojUE42tL0',
    appId: '1:69161896679:android:0450e20edf96fcc2037042',
    messagingSenderId: '69161896679',
    projectId: 'builder-jobs-app',
    storageBucket: 'builder-jobs-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASyzS4uT6j54pAL5PELjFUfmKMT_y99lc',
    appId: '1:69161896679:ios:c802dffd9dcdc6e6037042',
    messagingSenderId: '69161896679',
    projectId: 'builder-jobs-app',
    storageBucket: 'builder-jobs-app.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASyzS4uT6j54pAL5PELjFUfmKMT_y99lc',
    appId: '1:69161896679:ios:c802dffd9dcdc6e6037042',
    messagingSenderId: '69161896679',
    projectId: 'builder-jobs-app',
    storageBucket: 'builder-jobs-app.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8XPIla0vpUdWCZw_L29RaofSWjThKh_o',
    appId: '1:69161896679:web:2587581cf5cfd8c9037042',
    messagingSenderId: '69161896679',
    projectId: 'builder-jobs-app',
    authDomain: 'builder-jobs-app.firebaseapp.com',
    storageBucket: 'builder-jobs-app.firebasestorage.app',
  );
}
